### ISSUE TITLE
errors from PyDMImageView widget when starting designer

### ISSUE THREAD

**Issue by prjemian** [slaclab/pydm#582] opened 2019-11-19 20:36 UTC
**Describe the bug**
Starting designer (from pyqt=5.12) and this exception is reported to the console:

```
(bs) mintadmin@mint-vm:~/.../eclipse/pydm-prj$ designer
Exception occurred while running Qt Designer.
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/envs/bs/lib/python3.7/site-packages/pydm/widgets/qtplugin_base.py", line 114, in createWidget
    w = self.cls(parent=parent)
  File "/home/mintadmin/Apps/anaconda/envs/bs/lib/python3.7/site-packages/pydm/widgets/image.py", line 109, in __init__
    ImageView.__init__(self, parent, view=plot_item)
  File "/home/mintadmin/Apps/anaconda/envs/bs/lib/python3.7/site-packages/pyqtgraph/imageview/ImageView.py", line 119, in __init__
    self.ui.setupUi(self)
  File "/home/mintadmin/Apps/anaconda/envs/bs/lib/python3.7/site-packages/pyqtgraph/imageview/ImageViewTemplate_pyqt.py", line 146, in setupUi
    QtCore.QMetaObject.connectSlotsByName(Form)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

Designer: The custom widget factory registered for widgets of class PyDMImageView returned 0.
** WARNING Factory failed to create  "PyDMImageView"
```

**Expected behavior**
No exceptions when designer is started.

**Steps to Reproduce**

shown above

**Possible Solution**
n/a

**My Platform**

* linux OS
* `pydm                      1.8.0                      py_0    conda-forge`
* `pyqt                      5.12.3           py37hcca6a23_1    conda-forge`
* `pyqtgraph                 0.10.0           py37h28b3542_3  `
* `python                    3.7.4                h265db76_1`
* `qt                        5.12.5               hd8c4c69_1    conda-forge`
* `qtpy                      1.9.0                      py_0`

Note:  This is pydm from conda-forge, not any local modification.

**Additional context**

**Comment by hhslepicka** [comment] 2019-11-19 20:43
@prjemian that is due to python 3.7.4 and a fix that was added to pyqt 5.13.1.
For now I am using python <= 3.7.3. Sorry about that.

**Comment by prjemian** [comment] 2019-11-19 20:46
I confirm that:

```
(bs) mintadmin@mint-vm:~/.../eclipse/pydm-prj$ python --version
Python 3.7.4
```

For this conda environment, I could try dropping python back to 3.7.3 and confirming your work-around.  `conda install python=3.7.3`

**Comment by prjemian** [comment] 2019-11-19 20:49
confirmed:

```
(bs) mintadmin@mint-vm:~/.../eclipse/pydm-prj$ conda install python=3.7.3
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/mintadmin/Apps/anaconda/envs/bs

  added / updated specs:
    - python=3.7.3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.7.3               |       h5b0a415_0        35.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        35.7 MB

The following packages will be SUPERSEDED by a higher-priority channel:

  python                 pkgs/main::python-3.7.4-h265db76_1 --> conda-forge::python-3.7.3-h5b0a415_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.7.3         | 35.7 MB   | ################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(bs) mintadmin@mint-vm:~/.../eclipse/pydm-prj$ designer
(bs) mintadmin@mint-vm:~/.../eclipse/pydm-prj$ 
```

Keep this open as bug for python=3.7.4?

**Comment by hhslepicka** [comment] 2019-11-19 21:22
Sure thing! It is related to https://github.com/slaclab/pydm/issues/533 in which I describe it in a bit more depth but let's keep this one up as well to make sure that it is clean with the Image Widget when the issue is solved.

**Comment by prjemian** [comment] 2019-11-19 22:06
Looking through that issue, this one looks like a duplicate.

**Comment by hhslepicka** [comment] 2019-12-02 18:31
Closing as duplicated with #533 .

**Closed by hhslepicka** 2019-12-02 18:31 UTC
