### ISSUE TITLE
Add latch mode to PyDMPushButton

### ISSUE THREAD

**Issue by joaopmrod** [slaclab/pydm#298] opened 2018-04-24 20:05 UTC
Add latch mode to PyDMPushButton. Allow to chose value on press and value on release.

**Comment by mattgibbs** [comment] 2018-04-25 00:14
Is the idea that you click the button, and it stays in the “pressed down” state until you click a second time, when it pops up again?

**Comment by hhslepicka** [comment] 2018-04-25 00:44
I believe that the initial idea was to hold the button down pressed and not like that but this is in fact a good idea and maybe better than the initial.

**Comment by mattgibbs** [comment] 2018-04-25 01:04
Hahaha, @hhslepicka I was asking because I don’t like that idea.  We have some EDM panels with buttons that work that way, and it’s always hard to tell what the button is indicating (does “on” text mean it’s on now, or that it will be on if you press?) The momentary push button you are describing is fine with me though!

**Comment by hhslepicka** [comment] 2020-08-20 21:35
Quick update on this one...

Here what will be implemented are two new Properties that can be changed via Qt Designer:
- `releaseValue`: (similar to `pressValue` value to be written when the button is released
- `writeWhenRelease`: (bool) controls wether or not to write the `releaseValue` when releasing the mouse button.

**Comment by jacquelinegarrahan** [comment] 2020-08-25 19:03
For this feature, is it reasonable to enforce disabling the confirmation dialogue property as the dialogue cannot be clicked while holding the button down?

**Comment by jacquelinegarrahan** [comment] 2020-08-25 19:09
Likewise, should the password option also be disabled?

**Comment by hhslepicka** [comment] 2020-08-25 20:05
Those are very interesting questions.
How does it look with the confirmation and also password protection?
Does it run both right away?
I think that if something is password protected or it has a confirmation box it should prevail over the release write.
If we can get it so both happen in sequence it is fine by me.

**Comment by hhslepicka** [comment] 2020-08-25 20:58
@mattgibbs what is your view on this?

**Comment by jacquelinegarrahan** [comment] 2020-08-26 00:28
The result is that the two confirmation prompts load in succession after a click because releasing the button is required for the prompt. There is no control on the duration of the press, other than the response time to the second prompt.

![confirm_message](https://user-images.githubusercontent.com/25035114/91240894-449fb900-e711-11ea-8962-3609c22f6f42.gif)

**Comment by hhslepicka** [comment] 2020-08-26 00:45
There must be only one confirmation/password... the release is just an action after the press.

**Comment by jacquelinegarrahan** [comment] 2020-08-26 00:58
In that case, the write on release would happen immediately after the confirmation/password. The press value and release value would be set in succession. Is that desirable?

**Comment by hhslepicka** [comment] 2020-08-26 01:03
That will be tricky for relative puts since it can be that you go out of sync by not have yet received the value from the first write operation. I need to think more about it.

**Comment by rcardenes** [comment] 2020-09-16 20:26
Hi. I just found this issue looking through the list. Here at Gemini we have some custom EPICS records that use a two or three-step process to ensure validity of inputs and start an accion (MARK-PRESET-START or just MARK-START).

Some of our older DM screens (mostly for engineering) reflect this separately, but at some point we started using the "message button" feature to send consecutive messages (MARK at press, START at release). This feature (independently of if the button stays "latched" or not) would help a lot during migration to PyDM.

I see that the issue is old, and `PyDMPushButton` is still reacting only to `clicked`. Do you plan on merging code?  I need it rather soon so (initially) I won't wait, but I'd rather implement something to an "ideal" solution so that later changes are not too cumbersome. In that sense, what would be the preferred solution: generalizing PushButton or a specialized class? A separate issue just for the press/release functionality and keep this one just for latching?

I believe we can make a case for two different implementations. Latching could be achieved by extending PyDMPushButton to support toggling, with two variants: toggling back associated to an external event (CA update, timer, ...), or to a new click. The press/release functionality may be a bit more specialized and granting a separate class to avoid complicating things.

Thoughts?

**Comment by rcardenes** [comment] 2020-09-18 08:47
Ok, I just noticed that @hhslepicka actually discussed the implementation that will follow. I'll take that :-)

**Comment by hhslepicka** [comment] 2020-09-22 19:08
Hi @rcardenes, sorry for the delayed answer.
@jacquelinegarrahan has the implementation done, I need to do some tests for cases in which we have password protected or confirmation dialog. I will try to get it merged early next week.

I guess we can still implement the time/based and new click to represent the "release" functionality in the near future.
Thank you very much for the input on that.

**Comment by hhslepicka** [comment] 2021-02-26 22:04
Closed via #701.
@rcardenes sorry for the delay on getting this done.
Please feel free to reach out for additional options.

**Closed by hhslepicka** 2021-02-26 22:04 UTC
