### ISSUE TITLE
User defined tooltip is not being shown

### ISSUE THREAD

**Issue by fernandohds564** [slaclab/pydm#534] opened 2019-08-13 18:37 UTC
**Describe the bug**
User defined tooltips for PyDM widgets are not shown. If the widget channel connects, no tooltip is shown. if the widget channel does not connect, only the message "PV is disconnected" is shown.

**Expected behavior**
I expected the user defined tooltip to be shown in addition to the PyDM messages, such as "PV is disconnected".

**Steps to Reproduce**
 - Create a PyDMWidget with a valid channel (in my case it was a PyDMPushButton);
 - set a tooltip;
 - execute the application and verify if the tooltip is there.

**Possible Solution**
 A possible solution is implemented in the PR #535.

**My Platform**
    * Ubuntu 18.04;
    * Python v3.6.8;
    * PyDM v1.7.3+13.g091d9778;
    * Numpy v1.15.0;
    * PyQt v5.11.3;
    * Qt v5.11.3;
    * PyQtGraph v0.10.0;

**Comment by hhslepicka** [comment] 2019-08-13 19:55
@fernandohds564 I couldn't reproduce this issue here using the latest from master.
I tested it with a label...
Do you mind to send an `.ui` file that demonstrates the issue?

**Comment by fernandohds564** [comment] 2019-08-14 12:42
@hhslepicka, @anacso17 and I have found out that this bug is not triggered by `.ui` files.
All `QObjects` defined in `.ui` files are created and initialized without any of their properties set. All properties, including the channel, are set afterwards.
This bug is triggered by the call to` check_enable_state` in the `__init__` method of `PyDMWidget`. Since the channel is not defined at that point when we use `.ui` files, the method is not called because of the decorator `only_if_channel_set` and the bug does not happen.
However, if we define the channel in the object initialization the bug is triggered. Here follows an example:

```
import sys
from qtpy.QtWidgets import QWidget, QHBoxLayout
from pydm.application import PyDMApplication
from pydm.widgets import PyDMPushButton, PyDMLabel

class Wid(QWidget):
    def __init__(self):
        super().__init__(parent=None)
        lay = QHBoxLayout(self)
        pbt = PyDMPushButton(
            self, 'test',
            init_channel='BO-Glob:AP-SOFB:ApplyDelta-Cmd')
        pbt.setToolTip('test1')
        lay.addWidget(pbt)
        lbl = PyDMLabel(
            self, init_channel='BO-Glob:AP-SOFB:ClosedLoop-Sts')
        lbl.setToolTip('test2')
        lay.addWidget(lbl)

app = PyDMApplication()
wind = Wid()
wind.show()
sys.exit(app.exec_())
```

**Comment by fernandohds564** [comment] 2019-08-26 11:40
Hi @hhslepicka, were you able to reproduce the issue with the code I sent? I used some specific channel names, but you can replace them with any PV that I still think the issue will come up.

Am I using the library correctly or do you recommend to create the object with an empty channel and set it afterwards?

**Comment by YektaY** [comment] 2024-12-10 19:09
This issues was addressed in https://github.com/slaclab/pydm/pull/911

**Closed by YektaY** 2024-12-10 19:09 UTC
Labels: bug
