### ISSUE TITLE
launch bare ui file with pydm with additional arguments

### ISSUE THREAD

**Issue by vespos** [slaclab/pydm#824] opened 2022-04-08 22:17 UTC
**Describe the bug**
Error when launching pydm with additional arguments with a simple ui file

**Steps to Reproduce**
`pydm --hide-nav-bar myscreen.ui`

lead to the the error:
```
  File "/cds/group/pcds/pyps/conda/py39/envs/pcds-5.3.1/lib/python3.9/site-packages/PyQt5/uic/__init__.py", line 202, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 63
    from pydm --hide-nav-bar.widgets.embedded_display import PyDMEmbeddedDisplay
```
Clearly it is just parsing the whole command to the import instead of only the pydm bit.

**Possible Solution**
Ignore arguments when parsing?

**Comment by anleslac** [comment] 2022-05-10 23:12
Unfortunately, we are unable to reproduce your error. What version of pydm are you running? `pydm --version`

**Comment by YektaY** [comment] 2023-08-15 20:56
We are closing this issue, if it is still a concern please reopen the issue. Thank you

**Closed by YektaY** 2023-08-15 20:56 UTC
Labels: codeathon
